version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/workoutDB
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_WS_URL=ws://localhost:5000

volumes:
  mongo-data:
    driver: local
